# Generated by Django 4.0.5 on 2022-06-23 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('company1', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('title1', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('start_date1', models.DateField(blank=True, default=None, null=True)),
                ('end_date1', models.DateField(blank=True, default=None, null=True)),
                ('company2', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('title2', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('start_date2', models.DateField(blank=True, default=None, null=True)),
                ('end_date2', models.DateField(blank=True, default=None, null=True)),
                ('company3', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('title3', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('start_date3', models.DateField(blank=True, default=None, null=True)),
                ('end_date3', models.DateField(blank=True, default=None, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('s_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saveprofile.profile')),
            ],
        ),
    ]
